### ISSUE TITLE
Crash when initialize

### ISSUE THREAD

**Issue by lostopkk** [Glitchfiend/GlitchCore#1]
### What's the issue you encountered?

I can't use it because it crashes at the beginning when it starts
fabric version of the mod tough as nails

### How can the issue be reproduced?

1. install the mods(tough as nails, glitchcore)
2. run the game

### Logs

https://mclo.gs/yTLjwz9

### Mod Version

1.0.0.26

**Comment by Adubbz** [comment]
It appears that the dev jar was being uploaded to Modrinth for Fabric. This should now be fixed for subsequent builds. In the interim, the CurseForge build should be the correct one.

**Comment by lostopkk** [comment]
> It appears that the dev jar was being uploaded to Modrinth for Fabric. This should now be fixed for subsequent builds. In the interim, the CurseForge build should be the correct one.

https://mclo.gs/dumAY8k
it's still crashing

**Comment by Adubbz** [comment]
You need to update Tough As Nails as well, not just GlitchCore

**Comment by lostopkk** [comment]
> You need to update Tough As Nails as well, not just GlitchCore

I'm on the most updated version, I even waited for another update and it still gives the same crash

![image](https://github.com/Glitchfiend/GlitchCore/assets/50776714/697aba2e-4add-4507-ba31-537ca3612e12)

**Comment by Adubbz** [comment]
Try again now with GlitchCore 1.0.0.30+ and Tough As Nails 9.2.0.52+

**Comment by lostopkk** [comment]
> Try again now with GlitchCore 1.0.0.30+ and Tough As Nails 9.2.0.52+

still crashing
https://mclo.gs/ltxEoS4 <-- new log

**Comment by Adubbz** [comment]
Alright, I've just tested with Glitch Core 1.0.0.31 and it works correctly (Tough As Nails didn't need further updating). Apologies for all the crashes, unfortunately none of these occurred in a development environment

**Comment by lostopkk** [comment]
> Alright, I've just tested with Glitch Core 1.0.0.31 and it works correctly (Tough As Nails didn't need further updating). Apologies for all the crashes, unfortunately none of these occurred in a development environment

Solved! thanks man!
