### ISSUE TITLE
Crashing on client end when loading server.

### ISSUE THREAD

**Issue by JenniferWhite** [Glitchfiend/GlitchCore#3]
### What's the issue you encountered?

I am using Glitchcore Fabric 1.20.6-1.1.0.5 on both Client and Server side; however whenever I'm loading the server I get an error from the client end saying Exceptional Error before it crashes the game. When I load single player it loads perfectly fine with no problems just the amount of mods that make my modpack.

Server: 
![image](https://github.com/Glitchfiend/GlitchCore/assets/25069999/c89860c5-38ee-4429-98f8-bdb74ecddce2)

Singleplayer: 
![image](https://github.com/Glitchfiend/GlitchCore/assets/25069999/296e1d76-0ee4-48da-9537-39e5e7a36048)

### How can the issue be reproduced?

It repeats only by loading the server. 

### Logs

https://gist.github.com/JenniferWhite/e7e353c4e286f894611d013b37f50b33

### Mod Version

1.20.6-1.1.0.5

**Comment by BrennaBunnie** [comment]
seconding this issue! working fine in my singleplayer world but glitchcore throws the exact same error when trying to use an aternos server, even though my versions match. i've tried it without mods (all the ones i use are glitchcore dependent) and the sever works fine
https://mclo.gs/yTi85xh
ps. i've never shared a log before, hope this is enough

**Comment by y0urf1nalf4ntasy** [comment]
i'm having the same issue! working fine on singleplayer but when i add it to a server (aternos in this case) all i get is an error. i've made sure the mod is on the same version on my computer and the server and i still get issues, but everything works fine without the mod
![Minecraft_ 1 20 6 2024-05-11 4_00_41 PM](https://github.com/Glitchfiend/GlitchCore/assets/169554574/94042c05-d732-442a-a24b-9725d50daf86)

**Comment by Adubbz** [comment]
This issue was resolved yesterday. You need to update GlitchCore
