### ISSUE TITLE
Crash when trying to use a hoe on dirt block

### ISSUE THREAD

**Issue by Fidulus** [Glitchfiend/GlitchCore#5]
### What's the issue you encountered?

Minecraft 1.21
Neoforge 21.0.40

When trying to convert a dirt block into Farm-land the game crashes.
I tried different tools.

I am very sorry if GlitchCore is not the actual culprit, it just seems to me like it is.
I am still trying to understand whats written in the crash log and pinpoint the error.
I like using a lot of mods so if it´s something else please feel free to tell me.

### How can the issue be reproduced?

1. Equip a (wooden) hoe
2. right click any dirt block
3. crash

### Logs

with wooden hoe
https://pastebin.com/dWMi9AfE

with Meka-tool
https://pastebin.com/cDctUsZc

### Mod Version

2.0.0.1

**Comment by ImAK9** [comment]
Looks like they have to update for new NeoForge loader versions as ToolActions was renamed to ItemAbilities
