### ISSUE TITLE
Crafting is broken on the latest version

### ISSUE THREAD

**Issue by Kokiza70555** [Glitchfiend/GlitchCore#7]
### What's the issue you encountered?

nearly all of the vannila items are uncraftable

### How can the issue be reproduced?

just try to make sticks or a crafting table

### Mod Version

2.0.0.2

**Comment by Kokiza70555** [comment]
oh and its on neoforge

**Comment by Adubbz** [comment]
This is not a GlitchCore issue. This does not occur with just GlitchCore and NeoForge 21.0.86.
